name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  lint:
    name: run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-repo
      - run: pnpm run lint --max-warnings=0
  format:
    name: run format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-repo
      - run: pnpm prettier --check .
  build:
    name: run build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-repo
      - run: pnpm run build
  type-check:
    name: run type-check
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-repo
      - run: pnpm run type-check
  test:
    name: run test
    needs: [build]
    strategy:
      matrix:
        node_version: [18.x, 24.x]
        os: [ubuntu-latest]
        include:
          - node_version: 22.x
            os: windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-repo
        with:
          node-version: ${{ matrix.node_version }}
      - run: pnpm run test
